import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1AD927",
  },
  header: {
    flex: 2,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  expenseNameContainer: {
    flex: 1,
    flexDirection: "row",
    borderRadius: 15,
    backgroundColor: "#fff",
    padding: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  textHeader: {
    flex: 1,
    color: "#053751",
    marginHorizontal: 10,
    fontSize: 18,
    writingDirection: "auto",
    fontFamily: "Dirooz",
    textAlign: "center",
  },
  infoContainer: {
    flex: 8,
    backgroundColor: "#fff",
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
  },
  inputContainer: {
    flexDirection: "row",
    marginTop: 10,
    borderWidth: 1,
    borderColor: "#f2f2f2",
    borderRadius: 5,
    backgroundColor: "#f2f2f2",
    paddingBottom: 5,
  },
  searchBar: {
    backgroundColor: "white",
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
    borderTopWidth: 0,
    borderBottomWidth: 1,
    borderBottomColor: "#EBE8E8",
  },
  searchInput: {
    fontFamily: "IRANSansWeb_Bold",
    fontSize: 12,
    textAlign: "right",
    color: "#053751",
    justifyContent: "center",
  },
  textInput: {
    flex: 10,
    color: "#053751",
    fontFamily: "Dirooz",
    textAlign: "center",
    backgroundColor: "white",
    justifyContent: "center",
  },
  expenseContainer: {
    marginTop: 10,
    padding: 10,
    borderBottomColor: "#EBE8E8",
    borderBottomWidth: 1,
    textAlign: "center",
    fontSize: 16,
    fontFamily: "IRANSansWeb_Bold",
  },
  buttonContainer: {
    flex: 5,
    justifyContent: "flex-end",
    marginVertical: 20,
  },
  addButton: {
    elevation: 1,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#1AD927",
    borderRadius: 5,
    marginHorizontal: 30,
    marginVertical: 5,
    padding: 10,
    flexDirection: "row",
    justifyContent: "center",
  },
  addButtonText: {
    fontSize: 16,
    color: "#1AD927",
    alignSelf: "center",
    fontFamily: "IRANSansWeb_Bold",
    writingDirection: "auto",
  },
  removeButton: {
    elevation: 1,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "red",
    borderRadius: 5,
    marginHorizontal: 30,
    marginVertical: 10,
    padding: 10,
    flexDirection: "row",
    justifyContent: "center",
  },
  removeButtonText: {
    fontSize: 16,
    color: "red",
    paddingHorizontal: 10,
    alignSelf: "center",
    fontFamily: "IRANSansWeb_Bold",
    writingDirection: "auto",
  },
  validationText: {
    color: "red",
    padding: 5,
    fontFamily: "IRANSansWeb_Bold",
    fontSize: 12,
    textAlign: "center",
  },
});
