import { StyleSheet, Platform } from "react-native";
import colors from "../../assets/resources/colors";
import fonts from "../../assets/resources/fonts";
import common from "../../assets/resources/common";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.white,
  },
  screenTitleContainer: {
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.ultraLightGray,
    flexDirection: "row",
  },
  screenTitleText: {
    flex: 3,
    textAlign: "center",
    fontFamily: fonts.IranSans_Bold,
    fontSize: common.baseFontSize,
    padding: 5,
  },
  saveExpenseButtonContainer: {
    flex: 1,
    borderWidth: 1,
    justifyContent: "center",
    borderRadius: common.baseBorderRadius,
    borderColor: colors.mainColor,
  },
  saveExpenseButtonText: {
    textAlign: "right",
    alignSelf: "center",
    padding: 5,
    color: colors.mainColor,
    fontFamily: fonts.IranSans_Medium,
    fontSize: common.baseFontSize,
  },
  goBackIconContainer: {
    flex: 1,
    justifyContent: "center",
    padding: 5,
  },
  goBackIcon: {
    color: colors.textBlack,
  },
  header: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  headerTextInput: {
    width: "100%",
    color: colors.textBlack,
    marginHorizontal: 5,
    backgroundColor: colors.white,
    fontSize: 18,
    writingDirection: "auto",
    fontFamily: fonts.IranSans_Bold,
    borderRadius: 10,
    textAlign: "center",
  },
  infoContainer: {
    flex: 9,
    backgroundColor: colors.white,
  },
  searchInputContainer: {
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGray,
  },
  searchBar: {
    backgroundColor: colors.white,
    borderWidth: 1,
    borderRadius: common.baseBorderRadius,
    borderColor: colors.mainColor,
    margin: 10,
    padding: 10,
    textAlign: "center",
    fontSize: common.baseFontSize,
    fontFamily: fonts.IranSans_Light,
  },
  searchInput: {
    fontFamily: fonts.IranSans_Bold,
    fontSize: 12,
    textAlign: "right",
    color: colors.textBlack,
    justifyContent: "center",
  },
  inputContainer: {
    marginVertical: 10,
    marginHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: colors.lightGray,
    paddingBottom: 5,
  },
  expenseDescriptionContainer: {
    flexDirection: "row",
  },
  expenseCategoryContainer: {
    padding: 15,
    marginRight: 5,
    borderWidth: 1,
    borderColor: colors.mainColor,
    borderRadius: common.baseBorderRadius + 5,
    justifyContent: "center",
  },
  expenseCategoryIcon: {
    color: colors.mainColor,
  },
  textInput: {
    flex: 3,
    marginTop: 5,
    padding: 10,
    borderColor: colors.ultraLightGray,
    borderWidth: 1,
    borderRadius: common.baseBorderRadius,
    textAlign: "center",
    fontSize: 16,
    color: colors.textBlack,
    fontFamily: fonts.IranSans_Light,
  },
  splitOptionsContainer: {
    flexDirection: "row-reverse",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.white,
    marginVertical: 5,
    marginHorizontal: 5,
  },
  modalOutmostContainer: {
    backgroundColor: colors.white,
    flex: 2,
    padding: 10,
  },
  modalContentContainer: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 15,
    padding: 15,
  },
  showModalButton: {
    alignSelf: "center",
    borderWidth: 1,
    borderRadius: common.baseBorderRadius,
    backgroundColor: colors.white,
    borderColor: colors.mainColor,
    padding: 7,
    marginHorizontal: 2,
    marginTop: 10,
  },
  hideModalButton: {
    alignSelf: "center",
    borderWidth: 1,
    borderRadius: common.baseBorderRadius,
    backgroundColor: colors.white,
    borderColor: colors.red,
    padding: 5,
    margin: 5,
    marginTop: 10,
  },
  modalButtonText: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    color: colors.mainColor,
    fontFamily: fonts.IranSans_Medium,
    paddingHorizontal: 20,
  },
  radioButtonsContainer: {
    // padding: 10,
    marginVertical: 5,
    flexDirection: "row-reverse",
    justifyContent: "center",
  },
  radioButtonContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
  },
  radioButtonText: {
    textAlign: "center",
    alignSelf: "center",
    color: colors.textBlack,
    fontFamily: fonts.IranSans_Medium,
    fontSize: common.baseFontSize,
  },
  showGroupModalButtonContainer: {
    justifyContent: "center",
    flexDirection: "row",
    borderWidth: 1,
    marginVertical: 5,
    marginHorizontal: 60,
    padding: 5,
    borderRadius: common.baseBorderRadius,
    borderColor: colors.mainColor,
  },
  showGroupModalButtonText: {
    textAlign: "center",
    fontFamily: fonts.IranSans_Medium,
    fontSize: common.baseFontSize,
    color: colors.textBlack,
  },
  hideModalButtonText: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    color: colors.red,
    fontFamily: fonts.IranSans_Medium,
    paddingHorizontal: 20,
  },
  modalItemContainer: {
    marginTop: 5,
    borderWidth: 1,
    borderColor: colors.ultraLightGray,
    borderRadius: 10,
  },
  modalHeaderContainer: {
    marginBottom: 10,
  },
  modalNameText: {
    textAlign: "center",
    justifyContent: "center",
    color: colors.mainColor,
    fontFamily: fonts.IranSans_Bold,
    fontSize: 16,
  },
  modalShareText: {
    textAlign: "center",
    justifyContent: "center",
    color: colors.mainColor,
    fontSize: 14,
  },
  categoryContainer: {
    flexDirection: "row-reverse",
    padding: 10,
    borderWidth: 1,
    marginBottom: 5,
    borderRadius: common.baseBorderRadius,
    borderColor: colors.ultraLightGray,
  },
  categoryName: {
    fontFamily: fonts.IranSans_Medium,
    color: colors.textBlack,
    alignSelf: "center",
    paddingHorizontal: 5,
  },
  categoryIconContainer: {
    flex: 1,
    padding: 5,
    alignSelf: "center",
  },
  categoryIcon: {
    color: colors.mainColor,
  },
  groupItemContainer: {
    flexDirection: "row-reverse",
    padding: 10,
    borderWidth: 1,
    marginBottom: 5,
    borderRadius: common.baseBorderRadius,
    borderColor: colors.ultraLightGray,
  },
  groupName: {
    fontFamily: fonts.IranSans_Medium,
    color: colors.textBlack,
    alignSelf: "center",
    paddingHorizontal: 5,
  },
});
