import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1AD927",
  },
  header: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  textHeader: {
    textAlign: "center",
    color: "#fff",
    fontSize: 20,
    writingDirection: "auto",
    fontFamily: "IRANSansWeb_Bold",
  },
  infoContainer: {
    flex: 7,
    backgroundColor: "#fff",
    paddingHorizontal: 20,
    borderTopRightRadius: 20,
    borderTopLeftRadius: 20,
  },
  customInputContainer: {
    marginTop: 15,
  },
  label: {
    color: "#053751",
    fontFamily: "IRANSansWeb_Bold",
    textAlign: "right",
    paddingRight: 3,
    fontSize: 12,
  },
  inputContainer: {
    flexDirection: "row",
    marginTop: 5,
    borderWidth: 1,
    borderColor: "#f2f2f2",
    borderRadius: 10,
    backgroundColor: "#f2f2f2",
    paddingBottom: 5,
  },
  inputContainerError: {
    flexDirection: "row",
    marginTop: 5,
    borderWidth: 1,
    borderColor: "red",
    borderRadius: 10,
    backgroundColor: "#f2f2f2",
    paddingBottom: 5,
  },
  textInput: {
    flex: 10,
    color: "#053751",
    padding: 10,
    fontFamily: "Dirooz",
    textAlign: "right",
  },
  toggleIcon: {
    flex: 1,
    marginRight: 5,
    marginTop: 4,
    marginLeft: 10,
    justifyContent: "center",
    alignSelf: "center",
    alignContent: "center",
  },
  cancelIcon: {
    flex: 1,
    marginRight: 5,
    marginTop: 4,
    marginLeft: 15,
    justifyContent: "center",
    alignSelf: "center",
    alignContent: "center",
  },
  confirmIcon: {
    flex: 1,
    marginRight: 8,
    marginTop: 4,
    marginLeft: 5,
    justifyContent: "center",
    alignSelf: "center",
    alignContent: "center",
  },
  buttonContainer: {
    flex: 4,
    justifyContent: "flex-end",
    marginTop: 30,
    // marginHorizontal: 10,
    marginBottom: 20,
  },
  filledButton: {
    elevation: 2,
    backgroundColor: "#1AD927",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
  },
  outlinedButton: {
    elevation: 2,
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#1AD927",
  },
  filledButtonText: {
    fontSize: 18,
    color: "#fff",
    alignSelf: "center",
    fontFamily: "IRANSansWeb_Bold",
    writingDirection: "auto",
  },
  outlinedButtonText: {
    fontSize: 18,
    color: "#1AD927",
    alignSelf: "center",
    fontFamily: "IRANSansWeb_Bold",
    writingDirection: "auto",
  },
});
