import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1AD927",
  },
  infoContainer: {
    flex: 6,
    backgroundColor: "#fff",
  },
  inputContainer: {
    marginTop: 20,
    marginHorizontal: 10,
    borderBottomColor: "#cccccc",
  },
  textInput: {
    marginTop: 5,
    padding: 10,
    borderColor: "#cccccc",
    borderWidth: 1,
    borderRadius: 12,
    textAlign: "center",
    fontSize: 16,
    color: "#000",
    fontFamily: "Dirooz",
  },
  buttonContainer: {
    flex: 5,
    justifyContent: "flex-end",
    marginVertical: 20,
  },
  addButton: {
    elevation: 1,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#1AD927",
    borderRadius: 5,
    marginHorizontal: 30,
    marginVertical: 5,
    padding: 10,
    flexDirection: "row",
    justifyContent: "center",
  },
  addButtonText: {
    fontSize: 16,
    color: "#1AD927",
    alignSelf: "center",
    fontFamily: "IRANSansWeb_Bold",
    writingDirection: "auto",
  },
  removeButton: {
    elevation: 1,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "red",
    borderRadius: 5,
    marginHorizontal: 30,
    marginVertical: 10,
    padding: 10,
    flexDirection: "row",
    justifyContent: "center",
  },
  removeButtonText: {
    fontSize: 16,
    color: "red",
    paddingHorizontal: 10,
    alignSelf: "center",
    fontFamily: "IRANSansWeb_Bold",
    writingDirection: "auto",
  },
});
